// <auto-generated />
namespace SpiceProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewTablesOrdersAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTablesOrdersAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202102241614113_New Tables Orders Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
