// <auto-generated />
namespace Food.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newtableoderheader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newtableoderheader));
        
        string IMigrationMetadata.Id
        {
            get { return "202102270951297_new table oder header"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
